Modelo
Sistema de Tarjetas:
	 * Cada tarjeta es unica y personalizada
	 * Delivery a Domicilio(ahora bici dps??)
	 * Bajo costo por ahora esto es un problema ya que necesito mas hojas.
	 * Seguimiento de clientes
	 * Propaganda


 Objetivos:
	 * Sitios WEB
	 * Comprar fotocopiadora .
	 * Comprar repuestos para máquinas.
	 * Papelería para fotos ()
	 * Venta y Reparación de Impresoras
	 * Venta e instalación de Sistemas Continuos
	 * Impresiones de remeras
	 * Reparar impresoras de PyMEs (normalmente estan bien)

 Competidores: 
	 * Maquinas
	 * Local
	 * Ubicación
 Problemas o ventajas:
	1º Maquinas
	2º Ubicación
	3º Local
	4º Personal
	5º Bajar Costos {$2000/1000 hojas= 2 pe la hoja}
 Metas:
 	* QUE ES EL EXITO PARA ESTE NEGOCIO??
 	* BIEN DEFINIDO
 	* REALISTA FECHAS / MONTOS


